### ISSUE TITLE
When OA first loads image, it doesnt show calculations

### ISSUE THREAD

**Issue by rdkgit** [Theta-Limited/OpenAthenaAndroid#139]
After loading an image, OA marks the center but does not show the calculations, output for center field of vision.

**Comment by mkrupczak3** [comment]
I'm not sure if this is what we want for intended behavior. 

On the one hand, it helps prompt the user to tap elsewhere in the image, familiarizing them with the tap to locate interface in the process. 

On the other hand, it may be more confusing than helpful for a first time user.

We should do some hallway usability testing to see which is better

**Comment by mkrupczak3** [comment]
Added prompt for the user to alleviate this issue.
