### ISSUE TITLE
Check for presence of DEM API Key on application launch

### ISSUE THREAD

**Issue by mkrupczak3** [Theta-Limited/OpenAthenaAndroid#150]
...and direct the User to obtain and input an API Key if not present

**Comment by rdkgit** [comment]
This entire step should NOT be needed.  We obtained an OT key for bundling with Android app much like iOS app.

**Comment by mkrupczak3** [comment]
> This entire step should NOT be needed. We obtained an OT key for bundling with Android app much like iOS app.

If the user downloads app from GitHub or F-Droid, we will not be able to bundle a key. 

F-Droid does reproducible builds from source code and compares with the binary on our GitHub release. If we alter the build from the public source code to include a key, it would break reproducible builds.

There is a non-trivial community of users who prefer F-Droid over Google Play due to privacy and security concerns. We need to support these users as much as possible

**Comment by rdkgit** [comment]
Ahh, makes perfect sense.  Key bundled with GooglePlay app but not source nor alt app stores.
