### ISSUE TITLE
Add Support for Teal2 Drones

### ISSUE THREAD

**Issue by rdkgit** [Theta-Limited/OpenAthenaAndroid#159]
Add support for Teal2 drones.

**Comment by mkrupczak3** [comment]
It seems that for the Teal2 metadata, Camera yaw/pitch/roll is expressed relative to the airframe (rather than North, East, Down reference frame). To handle, sum the camera roll with platform roll, etc.

**Comment by mkrupczak3** [comment]
Initial support added in 234e07c7cba8e704208c0f2c39b5fb3fd9c5e092 based on estimated camera intrinsic values (sourced from tech spec document of the camera sensor). May improve with the addition of [calibrated values](https://github.com/Theta-Limited/camera-calibration)
