### ISSUE TITLE
Location over ocean and water

### ISSUE THREAD

**Issue by rdkgit** [Theta-Limited/OpenAthenaAndroid#165]
Search and rescue (e.g. Coast Guard) would like to be able to locate objects (boats, people, ships, etc.) in the ocean.  Currently, OA cannot get DEM data over oceans and thus terrain ray-casting algorithm won't work.  Need to detect this condition and use 0 MSL as terrain altitude.

**Comment by mkrupczak3** [comment]
Duplicate with #63
